package:
  name: utility_belt
  version: "0.0.0"

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  requires:
    - pytest
  imports:
    - utility_belt

about:
  home: add_url_here
  license: MIT License
